%%{init: {'flowchart': {'curve': 'linear'}}}%%
graph TD;
	__start__([<p>__start__</p>]):::first
	route(route)
	edit(edit)
	answer(answer)
	__end__([<p>__end__</p>]):::last
	__start__ --> route;
	answer --> __end__;
	edit --> __end__;
	route -.-> answer;
	route -.-> edit;
	classDef default fill:#f2f0ff,line-height:1.2;
	classDef first fill-opacity:0;
	classDef last fill:#bfb6fc;
